# Generated by Django 3.0.6 on 2020-05-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20200518_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sex',
            new_name='cinsiyet',
        ),
    ]
