# Generated by Django 3.0.6 on 2020-05-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_auto_20200518_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[(None, 'Cinsiyet'), ('diger', 'DİĞER'), ('erkek', 'ERKEK'), ('kadın', 'KADIN')], max_length=6, verbose_name='Cinsiyet'),
        ),
    ]
