# Generated by Django 3.0.4 on 2020-04-12 11:58

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='PageManager',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Category')),
            ],
            bases=('app.category',),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Alt Kategori')),
                ('topCategory', models.ManyToManyField(blank=True, to='app.Category')),
            ],
            options={
                'verbose_name_plural': 'Alt Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='ProductTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ürün Başlığı')),
                ('subcategory', models.ManyToManyField(blank=True, to='app.Subcategory')),
            ],
            options={
                'verbose_name_plural': 'Ürün Başlıkları',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name:')),
                ('icerik', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Content')),
                ('created_date', models.TimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='/img/default.jpg', upload_to=app.models.uplod_to, verbose_name='Image')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('ProductTitles', models.ManyToManyField(blank=True, to='app.ProductTitle')),
                ('Subcategorys', models.ManyToManyField(blank=True, to='app.Subcategory')),
                ('categorys', models.ManyToManyField(blank=True, to='app.Category')),
            ],
            options={
                'verbose_name_plural': 'Ürünler',
                'ordering': ['id'],
            },
        ),
    ]
