# Generated by Django 3.0.6 on 2020-05-16 14:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icerik',
            field=ckeditor.fields.RichTextField(max_length=5000, null=True, verbose_name='İçerik giriniz...'),
        ),
    ]
