# Generated by Django 3.0.6 on 2020-05-17 11:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200516_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='icerik',
            field=ckeditor.fields.RichTextField(help_text='Yorum yazınız.', max_length=5000, null=True, verbose_name='Yorum'),
        ),
    ]
