# Generated by Django 3.0.6 on 2020-05-19 08:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_favoritedblog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoritedBlog',
            new_name='FavoritedProduct',
        ),
    ]
