# Generated by Django 3.0.6 on 2020-05-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200519_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritedproduct',
            options={'verbose_name_plural': 'Favori Ürünler'},
        ),
    ]
