# Generated by Django 3.0.6 on 2020-05-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200519_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorys',
            field=models.ManyToManyField(blank=True, default='Elektronik', to='app.Category'),
        ),
    ]
