# Generated by Django 3.0.6 on 2020-05-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='following',
            options={'verbose_name_plural': 'Takipleşme Sistemi'},
        ),
    ]
